server:
   port: 8080
   
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/class_local_db
      username: root
      password: Borntowin1992
   jpa:
      properties:
         hibernate:
            show_sql: false
            format_sql: false
      database-platform: org.hibernate.dialect.MySQLDialect
   